### ISSUE TITLE
Incompatibility with `flake8-mutable` on python2

### ISSUE THREAD

**Issue by grundic** [ar4s/flake8_tuple#13]
Hello,

Found very weird behaviour: for some reason checks for your plugin being broken on python2 if the [flake8-mutable](https://github.com/ebeweber/flake8-mutable) is installed as well. It might be the problem of `flake8-mutable` plugin, but I didn't checked that.
Here is wtr:
```bash
/tmp ❯❯❯ virtualenv -p python2 flake8_tuple_virtual_env
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in flake8_tuple_virtual_env/bin/python2.7
Also creating executable in flake8_tuple_virtual_env/bin/python
Installing setuptools, pip, wheel...done.
/tmp ❯❯❯ source flake8_tuple_virtual_env/bin/activate
(flake8_tuple_virtual_env)/tmp ❯❯❯ pip install flake8 flake8-tuple
Collecting flake8
...
...
...
flake8_tuple_virtual_env)/tmp ❯❯❯ cat > dummy.py
foo = 'bar',
(flake8_tuple_virtual_env)/tmp ❯❯❯ flake8 dummy.py
dummy.py:1:7: T801 one element tuple  # Here validation works
(flake8_tuple_virtual_env)/tmp ❯❯❯ pip install flake8-mutable
Collecting flake8-mutable
...
...
...
flake8_tuple_virtual_env)/tmp ❯❯❯ flake8 dummy.py
(flake8_tuple_virtual_env)/tmp ❯❯❯ # And here not...
```

**Comment by grundic** [comment]
Yeah, forgot to mention: with python3 the same wtr works fine.

**Comment by ar4s** [comment]
Thanks for reporting! I will check that.

**Comment by ar4s** [comment]
I found bug in ``flake8-mutable`` https://github.com/ebeweber/flake8-mutable/blob/master/mutable_defaults.py#L33. If ``flake8-mutable`` run before ``flake8-tuple`` (or other checker) then ``flake8-mutable`` pops all nodes from tree.

**Comment by grundic** [comment]
Yeah, actually I also thought that the problem is in `mutable`: my tests were flaky when it was installed. After I removed it, everything was fine.
Thank you for investigation and PL, good job!
