### ISSUE TITLE
false negative: when expression is not a literal/reference

### ISSUE THREAD

**Issue by mbarkhau** [ar4s/flake8_tuple#14]
If the assignment uses an expression or function call the linter doesn't show the error.

    group_by = reference,                # T801 one element tuple
    group_by = "arg",                    # T801 one element tuple
    group_by = function_call("arg"),     # nada
    group_by = ("foobar" * 3),           # zilch

I've decided to go with the plugin from megapctr for now, but since you have the packaging working on pypi I would prefer if this worked here too.

https://github.com/megapctr/flake8-terse-tuple

**Comment by ar4s** [comment]
Thanks for reporting! I will check that and patch :)

**Comment by ar4s** [comment]
@mbarkhau please update flake8_tuple to 0.2.13 from PyPi
