### ISSUE TITLE
Build to wheel

### ISSUE THREAD

**Issue by PeterJCLaw** [ar4s/flake8_tuple#29]
Hi, Thanks for this great little project.

It would be great if this project supported building to wheels as this would speed up installation for users and mean that they didn't need to run `setup.py`.

I'd be happy to put together a PR for this at some point if you'd be open to merging it.
Likely I'd base this on a simple wrapper script I use in one of my existing projects that does the build to wheels and uploads both that and the `sdist` to PyPI using `twine`.

**Comment by ar4s** [comment]
Hi, I just uploaded `0.4.1`. The last time I forgot build and upload a wheel. 
You mentioned about some wrapper but I think that the following code:
```
python setup.py sdist bdist_wheel
python -m twine upload --repository pypi [or testpypi] dist/*
```
solves the problem. Feel free to open PR!

**Comment by PeterJCLaw** [comment]
Yup, those lines are pretty much all it is. In my [`tuck`](https://github.com/PeterJCLaw/tuck) project I have [a script](https://github.com/PeterJCLaw/tuck/blob/master/script/release/release) which does that build and release, plus checking that the version number being built matches the current git tag. The latter part is mostly to ensure I've tagged it before uploading as I prefer to tag my releases. (I also have that script run on Circle CI on tag builds, so that I can just push a tag and the rest is done for me.)

I realise that that tag/build/CI setup may not be to everyone's liking, so I'd only imagined adding the basic parts of the script as part of this. (Happy to share the rest if you'd like that too!)

**Comment by ar4s** [comment]
@PeterJCLaw thank you for your contribution!
